#!/bin/bash
# Detect USB audio device and generate /etc/asound.conf
# Run as ExecStartPre in rtesip.service

ASOUND_CONF="/etc/asound.conf"

# Find the first USB audio card number
USB_CARD=""
for card_dir in /proc/asound/card*/; do
    card_num=$(basename "$card_dir" | sed 's/card//')
    if [ -f "$card_dir/usbid" ]; then
        USB_CARD="$card_num"
        card_name=$(cat "/proc/asound/card${card_num}/id" 2>/dev/null || echo "USB")
        echo "Found USB audio: card $USB_CARD ($card_name)"
        break
    fi
done

if [ -z "$USB_CARD" ]; then
    echo "No USB audio device found — removing asound.conf"
    rm -f "$ASOUND_CONF"
    exit 0
fi

# Generate asound.conf with dmix/dsnoop for the detected card
cat > "$ASOUND_CONF" <<EOF
# Auto-generated by detect-audio.sh — USB audio card $USB_CARD
pcm.usb_play {
    type plug
    slave {
        pcm "dmix:${USB_CARD},0"
        rate 48000
    }
}

pcm.usb_cap {
    type plug
    slave {
        pcm "dsnoop:${USB_CARD},0"
        rate 48000
    }
}

pcm.!default {
    type asym
    playback.pcm usb_play
    capture.pcm usb_cap
}

ctl.!default {
    type hw
    card ${USB_CARD}
}
EOF

echo "Generated $ASOUND_CONF for card $USB_CARD"
