#!/bin/bash
# Detect USB audio device and generate /etc/asound.conf
# Run as ExecStartPre in rtesip.service

ASOUND_CONF="/etc/asound.conf"

# Find the first USB audio card number
USB_CARD=""
for card_dir in /proc/asound/card*/; do
    card_num=$(basename "$card_dir" | sed 's/card//')
    if [ -f "$card_dir/usbid" ]; then
        USB_CARD="$card_num"
        card_name=$(cat "/proc/asound/card${card_num}/id" 2>/dev/null || echo "USB")
        echo "Found USB audio: card $USB_CARD ($card_name)"
        break
    fi
done

if [ -z "$USB_CARD" ]; then
    echo "No USB audio device found — removing asound.conf"
    rm -f "$ASOUND_CONF"
    exit 0
fi

# Generate asound.conf with dmix/dsnoop and channel routing for the detected card
cat > "$ASOUND_CONF" <<EOF
# Auto-generated by detect-audio.sh — USB audio card $USB_CARD

# ── Base playback and capture (shared access via dmix/dsnoop) ──
pcm.usb_play {
    type plug
    slave {
        pcm "dmix:${USB_CARD},0"
        rate 48000
    }
}

pcm.usb_cap {
    type plug
    slave {
        pcm "dsnoop:${USB_CARD},0"
        rate 48000
    }
}

# ── Channel routing for capture (input) ──

# ll: Left input on both channels
pcm.cap_ll {
    type route
    slave.pcm "usb_cap"
    slave.channels 2
    ttable.0.0 1.0
    ttable.1.0 1.0
}

# rr: Right input on both channels
pcm.cap_rr {
    type route
    slave.pcm "usb_cap"
    slave.channels 2
    ttable.0.1 1.0
    ttable.1.1 1.0
}

# rl: Swap left and right inputs
pcm.cap_rl {
    type route
    slave.pcm "usb_cap"
    slave.channels 2
    ttable.0.1 1.0
    ttable.1.0 1.0
}

# mono: Mix both inputs to mono on both channels
pcm.cap_mono {
    type route
    slave.pcm "usb_cap"
    slave.channels 2
    ttable.0.0 0.5
    ttable.0.1 0.5
    ttable.1.0 0.5
    ttable.1.1 0.5
}

# ── Channel routing for playback (output) ──

# ll: Left output on both speakers
pcm.play_ll {
    type route
    slave.pcm "usb_play"
    slave.channels 2
    ttable.0.0 1.0
    ttable.0.1 1.0
}

# rr: Right output on both speakers
pcm.play_rr {
    type route
    slave.pcm "usb_play"
    slave.channels 2
    ttable.1.0 1.0
    ttable.1.1 1.0
}

# rl: Swap left and right outputs
pcm.play_rl {
    type route
    slave.pcm "usb_play"
    slave.channels 2
    ttable.0.1 1.0
    ttable.1.0 1.0
}

# mono: Mix both channels to mono on both speakers
pcm.play_mono {
    type route
    slave.pcm "usb_play"
    slave.channels 2
    ttable.0.0 0.5
    ttable.1.0 0.5
    ttable.0.1 0.5
    ttable.1.1 0.5
}

# ── Default: straight LR passthrough ──
pcm.!default {
    type asym
    playback.pcm usb_play
    capture.pcm usb_cap
}

ctl.!default {
    type hw
    card ${USB_CARD}
}
EOF

echo "Generated $ASOUND_CONF for card $USB_CARD"
